-- Creates the TOURNAMENTPRIZES table

USE [Tournaments]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TOURNAMENTPRIZES](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TournamentId] [int] NOT NULL,
	[PrizeId] [int] NOT NULL,
CONSTRAINT [PK_TOURNAMENTPRIZES] PRIMARY KEY CLUSTERED
(
	[Id] ASC
)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TOURNAMENTPRIZES]  WITH CHECK ADD  CONSTRAINT [FK_TOURNAMENTPRIZES_PRIZES] FOREIGN KEY([PrizeId])
REFERENCES [dbo].[PRIZES] ([Id])
GO

ALTER TABLE [dbo].[TOURNAMENTPRIZES] CHECK CONSTRAINT [FK_TOURNAMENTPRIZES_PRIZES]
GO

ALTER TABLE [dbo].[TOURNAMENTPRIZES]  WITH CHECK ADD  CONSTRAINT [FK_TOURNAMENTPRIZES_TOURNAMENTS] FOREIGN KEY([TournamentId])
REFERENCES [dbo].[TOURNAMENTS] ([Id])
GO

ALTER TABLE [dbo].[TOURNAMENTPRIZES] CHECK CONSTRAINT [FK_TOURNAMENTPRIZES_TOURNAMENTS]
GO
