-- Creates the MATCHUPENTRIES table

USE [Tournaments]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MATCHUPENTRIES](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[MatchupId] [int] NOT NULL,
	[ParentMatchupId] [int] NOT NULL,
	[TeamCompetingId] [int] NOT NULL,
	[Score] [float] NOT NULL,
CONSTRAINT [PK_MATCHUPENTRIES] PRIMARY KEY CLUSTERED
(
	[Id] ASC
)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MATCHUPENTRIES]  WITH CHECK ADD  CONSTRAINT [FK_MATCHUPENTRIES_TEAMS] FOREIGN KEY([TeamCompetingId])
REFERENCES [dbo].[TEAMS] ([Id])
GO

ALTER TABLE [dbo].[MATCHUPENTRIES] CHECK CONSTRAINT [FK_MATCHUPENTRIES_TEAMS]
GO